os:
  - osx
  - linux
  - windows
language: rust
rust:
  - stable
script:
  - cargo metadata --no-deps
  - cargo build --verbose --all --release
before_deploy:
  - mkdir -p target/build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];     then mv target/release/minecraft_downloader     target/build/minecraft_downloader_osx; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];   then mv target/release/minecraft_downloader     target/build/minecraft_downloader_linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mv target/release/minecraft_downloader.exe target/build/minecraft_downloader_windows.exe; fi
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d')-$(git log --format=%h -1)}
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: target/build/*
    skip_cleanup: true
    on:
      branch: master
