os:
  - linux
  - osx
  - windows
language: rust
rust:
  - stable
script:
  - cargo build --verbose --all --release
before_deploy:
  - git config --local user.name "travis.ci"
  - git config --local user.email "marblenix@users.noreply.github.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "target/release/minecraft_downloader"
    - "target/release/minecraft_downloader.exe"
  skip_cleanup: true
  on:
    tags: true
