[package]
name = "minecraft_downloader"
description = "Download Minecraft's server.jar file"
version = "0.3.0"
authors = ["Caleb Marble <marblenix@users.noreply.github.com>"]
edition = "2018"
homepage = "https://github.com/marblenix/minecraft_downloader"
repository = "https://github.com/marblenix/minecraft_downloader"
keywords = ["minecraft", "management", "utility"]
license = "MIT"
publish = false

[dependencies]
bytes = "*"
clap = "2"
futures = "*"
futures-core = "*"
futures-util = "*"
rust-crypto = "*"
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = "*"

[dependencies.reqwest]
features = ["blocking", "stream", "json"]
version = "*"

# Windows cannot statically link openssl libraries
[target.'cfg(unix)'.dependencies.openssl]
features = ["vendored"]
version = "*"
