[package]
name = "minecraft_downloader"
description = "Download Minecraft's server.jar file"
version = "0.2.0"
authors = ["Caleb Marble <marblenix@users.noreply.github.com>"]
edition = "2018"
homepage = "https://github.com/marblenix/minecraft_downloader"
repository = "https://github.com/marblenix/minecraft_downloader"
keywords = ["minecraft", "management", "utility"]
license = "MIT"
publish = false

[dependencies]
clap = "2"
rust-crypto = "*"
serde = "1"
serde_json = "1"
serde_derive = "1"

[dependencies.reqwest]
features = ["blocking", "stream", "json"]
version = "*"

# Windows cannot statically link openssl libraries
[target.'cfg(unix)'.dependencies.openssl]
features = ["vendored"]
version = "*"
