#!/usr/bin/env bash

set -eu

mkdir -p target/build

virustotal_url="https://www.virustotal.com/en/file/sha256here/analysis/"
release_info="$(curl -s "${GITHUB_API_ENDPOINT}/repos/${TRAVIS_REPO_SLUG}/releases/tags/${TRAVIS_TAG}")"
id="$(echo "${release_info}" | jq --raw-output .id)"
description="$(echo "${release_info}" | jq --raw-output .id)"
echo $release_info
echo $id
echo $description
#curl -s -X PATCH -H "Authorization: bearer ${GITHUB_API_KEY}" "${GITHUB_API_ENDPOINT}/repos/${TRAVIS_REPO_SLUG}/releases/${id}" -d '{"tag_name": "'${TRAVIS_TAG}'", "target_commitish": "master", "name": "'${TRAVIS_TAG}'", "body": "VirusTotal scan for .exe file: '${virustotal_url}'", "draft": false, "prerelease": false}'
