#!/usr/bin/env bash

set -eu

api() {
    method="$1"
    endpoint="$2"

    curl -s -X "${method}" -H "Authorization: bearer ${GITHUB_API_KEY}" "${GITHUB_API_ENDPOINT}${endpoint}"
}

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    release_id="$(api GET "/repos/${TRAVIS_REPO_SLUG}/releases/tags/latest" | jq .id)"
    for asset_id in $(api GET "/repos/${TRAVIS_REPO_SLUG}/releases/${release_id}/assets" | jq .[].id); do
        api DELETE "/repos/${TRAVIS_REPO_SLUG}/releases/assets/${asset_id}"
    done
    api DELETE "/repos/${TRAVIS_REPO_SLUG}/releases/${release_id}"
fi
