name: Rust

on:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Check for well formatted code
        run: cargo fix --all-targets --examples --workspace

      - name: Check project
        run: cargo check --release --verbose --workspace --all-targets --all-features

      - name: Check tests
        run: cargo test --release --verbose

      - name: Check Build
        run: cargo build --release --verbose

      - name: Check installation from source
        run: cargo install --verbose --all-features --path . --root install
