name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for well formatted code
        run: cargo fmt --all -- --check

      - name: Check project
        run: cargo check --verbose --workspace --all-targets --all-features

      - name: Check Build
        run: cargo build --verbose

      - name: Check tests
        run: cargo test --verbose

      - name: Check installation from source
        run: cargo install --path .

