name: Rust Release

on:
  push:
    tags: [v*]

jobs:
  build:
    strategy:
      matrix:
        run:
          - { name: linux,   label: ubuntu-latest,  ext: '' }
          - { name: macos,   label: macOS-latest,   ext: '' }
          - { name: windows, label: windows-latest, ext: .exe }
    name: ${{ matrix.run.name }} Build
    runs-on: ${{ matrix.run.label }}
    steps:
      - uses: actions/checkout@v6
      - run: cargo install --all-features --path . --root install
      - run: mv install/bin/minecraft_downloader${{ matrix.run.ext }} minecraft_downloader_${{ matrix.run.name }}${{ matrix.run.ext }}
      - uses: actions/upload-artifact@v7
        id: artifact
        with:
          path: minecraft_downloader_${{ matrix.run.name }}${{ matrix.run.ext }}
          if-no-files-found: error
          archive: false

  virustotal:
    name: Scan Binaries
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - name: Scan binaries
        run: >-
          find . -type f -iname '*minecraft_downloader*' -exec
          curl --silent --output /dev/null
          --url https://www.virustotal.com/api/v3/files
          --header "X-ApiKey: ${{ secrets.VIRUSTOTAL_API_KEY }}"
          --form file=@{} \;

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          make_latest: true
          fail_on_unmatched_files: true
          files: minecraft_downloader*
          body: |
            ## VirusToatal scans
            - [minecraft_downloader_linux](https://www.virustotal.com/en/file/${{ needs.build.outputs.linux }}/analysis)
            - [minecraft_downloader_macos](https://www.virustotal.com/en/file/${{ needs.build.outputs.macos }}/analysis)
            - [minecraft_downloader_windows.exe](https://www.virustotal.com/en/file/${{ needs.build.outputs.windows }}/analysis)